# Generated by Django 4.2.5 on 2023-09-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_course_title_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
